[project]
name = "dc26-vatican-explorer"
version = "0.1.0"
description = "---TODO---"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel",
    "jupyter",
]
scrape = [
    "requests",
]
data-manipulation = [
    "pandas",
]